TOPICS = {
    "travel": "Путешествия",
    "science": "Наука и технологии",
    "sport": "Спорт",
    "books": "Книги и фильмы",
    "everyday": "Быт"
}

WORDS = {
    "sport": {
        "a": ["team", "work out", "coach", "score", "warm up", "lose", "draw", "referee", "track", "field"],
        "b": ["athlete", "championship", "tournament", "stamina", "strategy", "penalty", "league", "fitness", "dribble", "setback"],
        "c": ["endurance", "agility", "coordination", "cool down", "push through", "pace oneself", "resilience", "elusive", "breakthrough", "peak performance"],
    },
    "travel": {
        "a": ["trip", "map", "ticket", "to go to", "to leave", "suitcase", "luggage", "to check in", "do the sights", "go abroad"],
        "b": ["itinerary", "accommodation", "explore", "landmark", "customs", "navigate", "flight", "destination", "fellow", "prevalent"],
        "c": ["excess weight", "locale", "quaint", "itinerant", "heritage", "seclusion", "traverse", "solitude", "track", "vessel"],
    },
    "science": {
        "a": ["science", "engine", "share", "update", "discover", "invent", "measure", "research", "observe", "analyze"],
        "b": ["hypothesis", "variable", "sustainability", "renewable", "efficiency", "carry out", "come up with", "look into", "roll out", "figure out"],
        "c": ["synthesize", "customize", "validate", "neural networks", "scale up", "zero in on", "weed out", "build on", "degree", "affirmation"],
    },
    "everyday": {
        "a": ["clean", "cook", "wash", "fix", "turn on", "hang up", "throw away", "sweep", "iron", "move in"],
        "b": ["rearrange", "refurbish", "stock up on", "wipe down", "sort out", "air out", "tighten", "reasoning", "to sustain", "to dispense"],
        "c": ["ambiance", "durable", "efficient", "intuitive", "seamless", "versatile", "ergonomic", "dimmable", "ductility", "tarnish"],
    },

    "books": {
        "a": ["book", "movie", "character", "plot", "writer", "review", "sequel", "flashback", "twist", "chapter"],
        "b": ["genre", "narrator", "cliffhanger", "consequence", "sort out", "screenplay", "tighten", "denouement", "understated", "fairy tale"],
        "c": ["ambiguous", "counterpart", "exaggeration", "haunting", "seamless", "vivid", "compelling", "evoke", "intricate", "engrossing"],
    },

}

TRANSLATES = {
    "team": "команда",
    "work out": "тренироваться",
    "coach": "тренер",
    "score": "счет",
    "warm up": "разминаться",
    "lose": "проиграть",
    "draw": "ничья",
    "referee": "судья",
    "field": "поле",
    "athlete": "спортсмен",
    "championship": "чемпионат",
    "tournament": "турнир",
    "stamina": "выносливость",
    "strategy": "стратегия",
    "penalty": "штраф",
    "league": "лига",
    "fitness": "физическая форма",
    "dribble": "дриблинг",
    "setback": "неудача",
    "endurance": "выносливость",
    "agility": "ловкость",
    "coordination": "координация",
    "cool down": "замедление",
    "push through": "преодолеть",
    "pace oneself": "распределять силы",
    "resilience": "устойчивость",
    "elusive": "неуловимый",
    "breakthrough": "прорыв",
    "peak performance": "пиковая форма",
    "trip": "поездка",
    "map": "карта",
    "ticket": "билет",
    "to go to": "посетить",
    "to leave": "отправляться",
    "suitcase": "чемодан",
    "luggage": "багаж",
    "to check in": "зарегистрироваться",
    "to change to": "пересаживаться на",
    "go abroad": "ехать за границу",
    "itinerary": "маршрут",
    "accommodation": "размещение",
    "explore": "исследовать",
    "landmark": "достопримечательность",
    "customs": "таможня",
    "navigate": "ориентироваться",
    "flight": "полет",
    "destination": "пункт назначения",
    "fellow": "попутчик",
    "prevalent": "распространенный",
    "excess weight": "избыточный вес",
    "locale": "место",
    "quaint": "живописный",
    "itinerant": "странствующий",
    "heritage": "наследие",
    "seclusion": "уединение",
    "traverse": "пересекать",
    "solitude": "одиночество",
    "track": "след",
    "vessel": "судно",
    "science": "наука",
    "engine": "двигатель",
    "share": "делиться",
    "update": "обновление",
    "discover": "обнаружить",
    "invent": "изобрести",
    "measure": "измерять",
    "research": "исследование",
    "observe": "наблюдать",
    "analyze": "анализировать",
    "hypothesis": "гипотеза",
    "variable": "переменная",
    "sustainability": "устойчивость",
    "renewable": "возобновляемый",
    "efficiency": "эффективность",
    "carry out": "выполнить",
    "come up with": "придумать",
    "look into": "изучить",
    "roll out": "раскатывать",
    "figure out": "выяснить",
    "synthesize": "синтезировать",
    "customize": "настраивать",
    "validate": "подтверждать",
    "neural networks": "нейронные сети",
    "scale up": "масштабировать",
    "zero in on": "сосредоточиться на",
    "weed out": "избавляться",
    "build on": "строить на основе",
    "degree": "степень",
    "affirmation": "утверждение",
    "clean": "чистить",
    "cook": "готовить",
    "wash": "мыть",
    "fix": "чинить",
    "turn on": "включать",
    "hang up": "вешать",
    "throw away": "выбрасывать",
    "sweep": "подметать",
    "iron": "гладить",
    "move in": "заселяться",
    "rearrange": "переставлять",
    "refurbish": "ремонтировать",
    "stock up on": "запасаться",
    "wipe down": "протирать",
    "air out": "проветривать",
    "tighten": "затягивать",
    "reasoning": "рассуждение",
    "to sustain": "поддерживать",
    "to dispense": "распределять",
    "ambiance": "атмосфера",
    "durable": "прочный",
    "efficient": "эффективный",
    "intuitive": "интуитивный",
    "seamless": "бесшовный",
    "versatile": "универсальный",
    "ergonomic": "эргономичный",
    "dimmable": "регулируемый",
    "ductility": "пластичность",
    "tarnish": "тускнеть",
    "book": "книга",
    "movie": "фильм",
    "character": "персонаж",
    "plot": "сюжет",
    "writer": "писатель",
    "review": "обзор",
    "sequel": "продолжение",
    "flashback": "воспоминания",
    "twist": "поворот",
    "chapter": "глава",
    "genre": "жанр",
    "narrator": "рассказчик",
    "cliffhanger": "захватывающий дух",
    "consequence": "последствие",
    "sort out": "разобраться",
    "screenplay": "сценарий",
    "denouement": "развязка",
    "understated": "сдержанный",
    "fairy tale": "сказка",
    "ambiguous": "двусмысленный",
    "counterpart": "аналог",
    "exaggeration": "преувеличение",
    "haunting": "навязчивый",
    "vivid": "яркий",
    "compelling": "захватывающий",
    "evoke": "вызывать",
    "intricate": "запутанный",
    "engrossing": "увлекательный",
}

MINCONN = 1
MAXCONN = 10

LIMIT_TIME_EVENTS = 10
LIMIT_USES = 10
LIMIT_LINK_USES = 3
LIMIT_USES_MESSAGES = 30

MODEL = "gpt-3.5-turbo"
TEMPERATURE = 0.2
MAX_TOKENS = 200
