name: Deploy Bot

on:
  push:
    branches:
      - main  # или другая основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest  # Или другой runner с нужными ресурсами

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Log system resources before deployment
        run: |
          echo "Logging system resources..." > $GITHUB_WORKSPACE/deploy_log.txt
          free -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          echo "CPU usage before deployment:" >> $GITHUB_WORKSPACE/deploy_log.txt
          top -n 1 | head -n 10 >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          echo "Disk usage before deployment:" >> $GITHUB_WORKSPACE/deploy_log.txt
          df -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Start deploying..." >> $GITHUB_WORKSPACE/deploy_log.txt
            cd /root/wordbi_bot
            git reset --hard HEAD >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 || { echo "Git reset failed"; exit 1; }
            git pull origin main >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 || { echo "Git pull failed"; exit 1; }
            source venv/bin/activate >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 || { echo "Failed to activate virtualenv"; exit 1; }
            pip install -r requirements.txt >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 || { echo "Failed to install dependencies"; exit 1; }
            pkill -f main.py >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 || echo "No process found to kill"
            nohup python3 main.py >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1 &
            echo "Deployment completed" >> $GITHUB_WORKSPACE/deploy_log.txt
            cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов

      - name: Log system resources after deployment
        run: |
          echo "Logging system resources after deployment..." >> $GITHUB_WORKSPACE/deploy_log.txt
          free -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          top -n 1 | head -n 10 >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          df -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов

      - name: Check processes after deployment
        run: |
          ps aux | grep python >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов

      - name: Display the logs from deploy_log.txt
        run: |
          echo "Displaying deploy logs..."
          cat $GITHUB_WORKSPACE/deploy_log.txt
