name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Используйте стандартный action для клонирования репозитория

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/wordbi_bot
            git reset --hard HEAD
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f main.py || echo "No process found to kill"
            nohup python3 main.py > /root/wordbi_bot/nohup.out 2>&1 &
            tail -f /root/wordbi_bot/nohup.out  # Для отображения логов
