name: Deploy Bot

on:
  push:
    branches:
      - main  # или другая основная ветка

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Или другой runner с нужными ресурсами
    timeout-minutes: 90  # Увеличиваем время на выполнение до 90 минут

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/share/powershell /usr/local/lib/heroku
          docker image prune -af
          sudo rm -rf /var/lib/apt/lists/*
          df -h

      - name: Disable verbose logging
        run: echo 'GITHUB_ACTIONS_RUNNER_VERBOSE=0' >> $GITHUB_ENV

      # Добавлен шаг для тестирования SSH-соединения
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection"
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} echo "SSH connection successful"

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 10G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Log system resources before deployment
        run: |
          echo "Logging system resources..." > $GITHUB_WORKSPACE/deploy_log.txt
          free -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          echo "CPU usage before deployment:" >> $GITHUB_WORKSPACE/deploy_log.txt
          top -n 1 | head -n 10 >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          echo "Disk usage before deployment:" >> $GITHUB_WORKSPACE/deploy_log.txt
          df -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов для проверки

      - name: Check system resources before SSH
        run: |
         echo "Available Disk Space:"
         df -h
         echo "Available Memory:"
         free -h
         echo "Running Processes:"
         ps aux --sort=-%mem | head -n 10

      - name: Connect to server and deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/wordbi_bot
            git reset --hard HEAD
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f main.py || echo "No process found"
            nohup python3 main.py &

      - name: Log system resources after deployment
        run: |
          echo "Logging system resources after deployment..." >> $GITHUB_WORKSPACE/deploy_log.txt
          free -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          top -n 1 | head -n 10 >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          df -h >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов для проверки

      - name: Check processes after deployment
        run: |
          ps aux | grep python >> $GITHUB_WORKSPACE/deploy_log.txt 2>&1
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод логов для проверки

      - name: Display the logs from deploy_log.txt
        run: |
          echo "Displaying deploy logs..."
          cat $GITHUB_WORKSPACE/deploy_log.txt  # Вывод всех логов в конце
