name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Используйте стандартный action для клонирования репозитория

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Start deploying..." > /root/wordbi_bot/deploy_log.txt
            cd /root/wordbi_bot
            git reset --hard HEAD >> /root/wordbi_bot/deploy_log.txt 2>&1 || { echo "Git reset failed"; exit 1; }
            git pull origin main >> /root/wordbi_bot/deploy_log.txt 2>&1 || { echo "Git pull failed"; exit 1; }
            source venv/bin/activate >> /root/wordbi_bot/deploy_log.txt 2>&1 || { echo "Failed to activate virtualenv"; exit 1; }
            pip install -r requirements.txt >> /root/wordbi_bot/deploy_log.txt 2>&1 || { echo "Failed to install dependencies"; exit 1; }
            pkill -f main.py >> /root/wordbi_bot/deploy_log.txt 2>&1 || echo "No process found to kill"
            nohup python3 main.py >> /root/wordbi_bot/deploy_log.txt 2>&1 &
            echo "Deployment completed" >> /root/wordbi_bot/deploy_log.txt
